projects:
  Recipe App:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: qdch4h72fzfivfzqkbvgrgdfu4
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://u2j5fswaxjdibb7dnomsyx756u.appsync-api.us-east-1.amazonaws.com/graphql
